### ISSUE TITLE
[PE-D] Invalid date error message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-2/tp#199]
It could be better to prompt the wrong date format specifically. For example: “The date entered is out of range, please check again!” 
Because the format of date entered is correct in term of the example you provided.
![ped_3.png](https://raw.githubusercontent.com/peng-217/ped/main/files/b5bb42f4-848e-4b62-9dd0-abd65e1ec36d.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: peng-217/ped#3

**Comment by JMattChiam** [comment]
closed with #258
