### ISSUE TITLE
[PE-D] Would expect search from inside to run only for that workout

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-2/tp#211]
![image.png](https://raw.githubusercontent.com/mudkip8/ped/main/files/62788aac-8f8a-4c35-a32b-c6be49741777.png)

Seeing workouts from inside workout is weird

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: mudkip8/ped#7

**Comment by JMattChiam** [comment]
Can just specify the behaviour in UG. tbh i think it's fine. Most people wouldn't need to search for exercises only when they're inside the workout unless they have an unrealistically long workout
