### ISSUE TITLE
[PE-D] [help] help help

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-2/tp#212]
![Screenshot 2021-10-29 at 5.05.50 PM.png](https://raw.githubusercontent.com/flerovious/ped/main/files/e9b1b659-4db7-48b3-bd10-9ec45075f9c0.png)
help for help command gave overall help information instead of help specific to the help command

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: flerovious/ped#5

**Comment by JMattChiam** [comment]
closed with #258
