### ISSUE TITLE
[PE-D] Remove function are able to take in parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-2/tp#233]
![image.png](https://raw.githubusercontent.com/tttyyzzz/ped/main/files/44847965-51e1-4d4b-b4ca-ad044026913b.png)

User are able to key in multiple inputs into remove function.
Values behind are ignored.
Good to put in user guide.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: tttyyzzz/ped#6

**Comment by JMattChiam** [comment]
closed with #258
