### ISSUE TITLE
[PE-D] Long user input might cause issues

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-2/tp#236]
![image.png](https://raw.githubusercontent.com/tttyyzzz/ped/main/files/5d264934-7757-4af7-b0cb-c7eea415949b.png)

As above.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: tttyyzzz/ped#7

**Comment by jonathanmui4** [comment]
This is an invalid bug.
